<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ig_history"
 *
 * Auto generated by Extension Builder 2018-11-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'History',
    'description' => 'Shows the history as a timeline.',
    'category' => 'plugin',
    'author' => 'Marvin Rudolph',
    'author_email' => 'm.rudolph@i-group.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
